
services:
  postgres:
    image: postgres:18
    env_file: .env
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "outposts"
      POSTGRES_DB: "postgres"
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - 9005:5432
    networks:
      - outposts
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -h 127.0.0.1 -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  outposts:
    driver: bridge
